name: timesync
version: '${project.version}'
main: de.fuchscrafter.timesyncplugin.Timesync
api-version: '1.19'
authors: [FuchsCrafter]
description: Synchronises the server's time to real time
website: fuchscrafter.de
commands:
  timesync:
    description: Shows information about the state of the plugin
    usage: /timesync
    permission: timesync.command